### ISSUE TITLE
### use cssVariables instead of  hardcoded boardSize in css:

### ISSUE THREAD

**Issue by shlomogcap** [ETLDevs/tic-tac-toe#4]
### use cssVariables:

- [x] add ":root" section with --board-size variable:
```
:root{
   --board-size: 3;
}
```
- [x] update you style to something like:
`grid-template-columns: repeat(var(--board-size), auto);`
- [x] then in you js you can do something like:
```
document.documentElement.style.setProperty('--board-size', YOUR_NEW_SIZE);
```

---
see this [post for example](https://css-tricks.com/updating-a-css-variable-with-javascript/)

_Originally posted by @shlomogcap in https://github.com/ETLDevs/tic-tac-toe/pull/3#discussion_r1040649400_

**Comment by ETLDevs** [comment]
I already did this before merging betterCode branch
